import Image from "next/image";
import Link from "next/link";
import {
  ArrowRight,
  Check,
  Eye,
  FileCheck2,
  Fingerprint,
  HeartHandshake,
  LockKeyhole,
  ScanSearch,
  ShieldCheck,
  Sparkles,
  WandSparkles,
} from "lucide-react";
import { SiteFooter } from "@/components/SiteFooter";
import { SiteHeader } from "@/components/SiteHeader";

const process = [
  { icon: Fingerprint, title: "Set your boundaries", text: "Choose what the AI may change. Face, hair, skin, background, and your own preserve zones stay protected." },
  { icon: WandSparkles, title: "Try on the garment", text: "YouCam generates the apparel preview from your photo and selected clothing reference." },
  { icon: ScanSearch, title: "Check every change", text: "Garment-aware checks inspect the face, skin, silhouette, protected zones, and everything outside the edit." },
  { icon: FileCheck2, title: "Approve with evidence", text: "Review findings, repair supported drift, and keep an integrity receipt—or delete everything immediately." },
];

export default function Home() {
  return (
    <div className="page-shell">
      <SiteHeader />
      <main id="main-content">
        <section className="hero">
          <div className="container hero-grid">
            <div>
              <span className="eyebrow"><span className="eyebrow-line" />Consent-first virtual try-on</span>
              <h1 className="serif">Change the clothes, <em>not the person.</em></h1>
              <p className="hero-copy">Tell AI what it may edit. KeepMe verifies that your face, skin, body, hair, and personally important details still look like you.</p>
              <div className="hero-actions">
                <Link className="btn btn-primary btn-wide" href="/studio">Try a garment safely <ArrowRight size={16} /></Link>
                <a className="btn btn-secondary" href="#how-it-works">See how it works</a>
              </div>
              <div className="micro-copy">
                <span><LockKeyhole size={13} /> Session-only images</span>
                <span><Eye size={13} /> No identity recognition</span>
                <span><Check size={13} /> You approve the result</span>
              </div>
            </div>
            <div className="hero-visual" aria-label="A synthetic shopper wearing a rust jacket, accompanied by a passed integrity contract">
              <div className="image-arch">
                <Image src="/demo/youcam-live-tryon.jpg" alt="Synthetic shopper wearing a rust utility jacket generated by YouCam Clothes v3" fill preload sizes="(max-width: 960px) 90vw, 48vw" />
              </div>
              <div className="hero-stamp"><span><ShieldCheck size={27} /><br />Checked<br />by KeepMe</span></div>
              <div className="contract-float">
                <div className="contract-float-top"><span>Identity Contract</span><span className="pass-badge"><Check size={10} /> passed</span></div>
                <div className="contract-row"><Check size={12} /> Face &amp; glasses preserved</div>
                <div className="contract-row"><Check size={12} /> Skin appearance stable</div>
                <div className="contract-row"><Check size={12} /> Background unchanged</div>
              </div>
            </div>
          </div>
        </section>

        <div className="trust-strip" aria-label="Product guarantees">
          <div className="container trust-inner">
            <div className="trust-item"><ShieldCheck size={18} /><span><strong>User-defined</strong> protections</span></div>
            <div className="trust-item"><ScanSearch size={18} /><span><strong>Multi-signal</strong> verification</span></div>
            <div className="trust-item"><LockKeyhole size={18} /><span><strong>Delete by default</strong> privacy</span></div>
            <div className="trust-item"><HeartHandshake size={18} /><span><strong>No sensitive-trait</strong> inference</span></div>
          </div>
        </div>

        <section className="section" id="how-it-works">
          <div className="container">
            <span className="section-kicker">A better contract with AI</span>
            <h2 className="section-title serif">From blind trust to visible proof.</h2>
            <p className="section-lede">A virtual try-on should answer one question: “How does this garment look on me?” KeepMe keeps the rest of you out of scope.</p>
            <div className="process-grid">
              {process.map(({ icon: Icon, title, text }, index) => (
                <article className="process-card" key={title}>
                  <div className="process-num"><span>0{index + 1}</span><ArrowRight size={14} /></div>
                  <div className="process-icon"><Icon size={21} /></div>
                  <h3>{title}</h3><p>{text}</p>
                </article>
              ))}
            </div>
          </div>
        </section>

        <section className="statement" id="why">
          <div className="container statement-grid">
            <blockquote>“You asked to try on a garment. You didn’t ask to become someone else.”</blockquote>
            <div className="statement-copy"><strong>Identity is not a model setting.</strong> It is personal. KeepMe lets each shopper preserve any visible detail without naming, classifying, or explaining why it matters.</div>
          </div>
        </section>

        <section className="section">
          <div className="container">
            <span className="section-kicker">Built for shared benefit</span>
            <h2 className="section-title serif">Trust for shoppers. Better signals for retailers.</h2>
            <div className="community-grid">
              <article className="community-card">
                <div className="community-icon"><HeartHandshake size={26} /></div>
                <h3>Preserve what matters—without explaining why.</h3>
                <p>Glasses, scars, assistive objects, religious garments, hair, or any custom region. The user draws the boundary; KeepMe never infers the meaning.</p>
                <Link className="text-link" href="/studio">Experience the shopper flow <ArrowRight size={14} /></Link>
              </article>
              <article className="community-card">
                <div className="community-icon"><Sparkles size={26} /></div>
                <h3>Learn where VTO fails—without seeing customer photos.</h3>
                <p>Aggregated reason codes reveal garment and model failure patterns. Small cohorts are suppressed and no demographic labels are generated.</p>
                <Link className="text-link" href="/dashboard">View retailer insights <ArrowRight size={14} /></Link>
              </article>
            </div>
          </div>
        </section>

        <section className="section" style={{ paddingTop: 0 }}>
          <div className="container cta-panel">
            <div><h2>Keep the garment preview. Keep yourself, too.</h2><p>Build your first Identity Contract in under a minute.</p></div>
            <Link className="btn btn-primary btn-wide" href="/studio">Start safe try-on <ArrowRight size={16} /></Link>
          </div>
        </section>
      </main>
      <SiteFooter />
    </div>
  );
}
